# Generated by Django 4.2.2 on 2023-07-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_registration', models.TextField(max_length=20)),
                ('car_description', models.TextField(max_length=250)),
                ('car_mileage', models.CharField(max_length=8)),
                ('car_transmission', models.CharField(choices=[('A', 'Auto'), ('M', 'Manual')], max_length=8)),
                ('car_seats', models.CharField(choices=[('3', '3 Adults'), ('4', '4 Adults'), ('5', '5 Adults')], max_length=10)),
                ('car_luggage', models.CharField(choices=[('2', '2 Bags'), ('3', '3 Bags'), ('4', '4 Bags')], max_length=10)),
                ('car_fuel', models.CharField(choices=[('P', 'Petrol'), ('O', 'Octane'), ('E', 'Electric')], max_length=10)),
                ('car_images', models.ImageField(upload_to='cars_image')),
                ('available_now', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
