# Generated by Django 4.2.2 on 2023-06-27 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cars.car')),
                ('price_hourly', models.CharField(max_length=50)),
                ('price_daily', models.CharField(max_length=50)),
                ('price_leasing', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
