# Generated by Django 4.2.2 on 2023-07-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=30, null=True)),
                ('price_hourly', models.CharField(max_length=8)),
                ('price_daily', models.CharField(max_length=8)),
                ('price_leasing', models.CharField(max_length=8)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
