# Generated by Django 4.2.2 on 2023-07-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=50)),
                ('from_destination', models.CharField(max_length=50)),
                ('to_destination', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('price_type', models.CharField(choices=[('Leasing', 'L'), ('Hourly', 'H'), ('Daily', 'D')], max_length=8)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.DateField()),
                ('end_time', models.DateField()),
                ('ordered_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('deleted_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
